### ISSUE TITLE
Curious About SSG flag

### ISSUE THREAD

**Issue by resistorsoftware** [stackbit-themes/fresh-nextjs#4]
Currently this theme builds with setting in stackbit.yaml as:

    ssgName: unibit

So it builds out the public directory with the CLI command **unibit develop**

So now, I want to place my developed site at github pages. I naively changed the ssgName to Jekyll to see what would happen, but that broke. I clearly am missing some changes. If I change the buildCommand to be something like jekyll build, the build fails as there is no expected _config.yml like Jekyll needs.

So what is this unibit conversion to Jekyll all about? I did not get any explanation from the site about just how this flexible unibit CLI can be used.

**Comment by smnh** [comment]
Hi,

Generally you have two options:
1. Use [Unibit](https://docs.stackbit.com/unibit/) as a standalone SSG with its [build](https://docs.stackbit.com/unibit/unibit-cli/#unibit_build) and [develop](https://docs.stackbit.com/unibit/unibit-cli/#unibit_develop) commands.
2. Use [Stackbit app](https://app.stackbit.com/dashboard) to convert Unibit Fresh theme to Jekyll (or any other supported SSG) and create new Jekyll site that will be added as a new repository in your GitHub account.

* Unibit is Stackbit's SSG that can be used stand alone or converted to another SSG (the conversion is made by internal Stackbit process when creating new projects via Stackbit)

**Comment by resistorsoftware** [comment]
So my question is this now. 

Using the command **unibit develop** I have a perfect website previewed on my localhost. Everything is in /public. Do I just copy that to my github pages repository and use the **.nojekyll** flag? 

Or so I now have to use Stackbit itself to accept my unibit repository, and ask it to convert to Jekyll, at which point it generates some Jekyll code just for me to use? 

It is not clear at all how this works.

**Comment by smnh** [comment]
Hi,
In order to build production site, you should run `unibit build` instead of `unibit develop`.
After that it will create a static site under `/public` folder as you noted.
Then you can publish this folder as is. I am not sure what `.nojekyll` flag does. I am assuming it just publishes content of static folder as is. If this is the case, then yes, you can do that.

If you use Stackbit to "transpile" your Unibit theme to Jekyll theme, it will do that only for you and will create new Jekyll site inside your GitHub.

**Comment by resistorsoftware** [comment]
I would love to know more about the transpile option. Straight up, I am happy with the build. I am just missing the explanation of how that concept of a specific build works. If I change the target from unibit to Jekyll, the build fails as it cannot find the files it needs to satisfy the build. A Jekyll build, for example, needs an _config.yml file, and this is just not present in the unibit theme. 

So I guess for the time being, I will set that aside, and try out the lifestyle of this by just moving /public back and forth to my Github pages and being happy that works.

**Comment by smnh** [comment]
The transpilation process is currently proprietary. But can be done by visiting app.stackbit.com and choosing one of the available Unibit themes, or providing your own. Once all other options are selected, such as CMS and SSG, Stackbit will convert the Unibit theme into Jekyll theme (or any other selected SSG). The converted theme will be put into a new GitHub repository and from then on can be used to build static sites.

Note, that if converted to Jekyll, GitHub Pages will not be able to build it because the generated Jekyll site will have filters and functions that GitHub pages do not support. That's why Stackbit connects the created repository to Netlify that will build and publish it instead.

**Comment by TomasBankauskas** [comment]
I’m closing this issue because it has been inactive for a while.
